name: Dependent Jobs Test
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
            - name: echo a string
              run: echo "Hello World"

            - name: Get environment versions
              run: |
                echo "Checking environment versions"
                echo "Node Version: $(node --version)"
                echo "NPM Version: $(npm --version)"
                echo "NuGet Version: $(nuget help | grep Version)"

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
            - name: echo a string
              run: echo "Hello World"

            - name: Get environment versions
              run: |
                echo "Checking environment versions"
                echo "Node Version: $(node --version)"
                echo "NPM Version: $(npm --version)"
                echo "NuGet Version: $(nuget help | grep Version)"