name: Dependent Jobs Test
on: [push]

jobs:
  run-in-ubuntu:
    runs-on: ubuntu-latest
    steps:
            - name: echo a string
              run: echo "Hello World"

            - name: Get environment versions
              run: |
                echo "Checking environment versions"
                echo "Node Version: $(node --version)"

  run-in-windows:
    needs: deploy
      runs-on: windows-latest
          steps:
            - name: echo a string
              run: echo "Hello World"

            - name: Get environment versions
              run: |
                echo "Checking environment versions"
                echo "Node Version: $(node --version)"
    macos-parallel-job:
      runs-on: macos-latest
          steps:
          - name: View SW Version
            run: sw_vers
