name: Terraform ci test 
run-name: ${{ github.actor }} testing make file for docker build

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    os-update:
        runs-on: ubuntu-latest
        steps:
            - shell: bash
            - uses: actions/checkout@v4            
              run: |
                sudo apt-get update
      
    install-make:
        needs: os-update
        runs-on: ubuntu-latest
        steps:
            - shell: bash
            - uses: actions/checkout@v4
              run: |
                sudo apt-get install make
                make --version

    make-version:
        needs: install-make
        runs-on: ubuntu-latest
        steps:
            - shell: bash
            - uses: actions/checkout@v4            
              run: |
                make --version
                echo "Make Version: $(make --version | head -n1) ,flag =  ${{ github.actor }}"


    make-docker-cmd:
        needs: install-make
        runs-on: ubuntu-latest
        
        steps:
            - shell: bash
            - uses: actions/checkout@v4

              run: |
                 make docker_build IMG=testing-img-pr