name: learn-docker-ci
run-name: ${{ github.actor }}  testing docker make shell run

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    install-make:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - shell: bash
              run: |
                sudo apt-get update
                sudo apt-get install make
            - shell: bash
              run: |
                make docker_build IMG=learn-docker-ci
            # - shell: bash
            #   run: |
            #     make docker_login 