name: Terraform ci test 
run-name: ${{ github.actor }} is Testing Terraform github actions

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
    os-update:
        runs-on: ubuntu-latest
        steps:
            - shell: bash
              run: |
                sudo apt-get update
      
    install-make:
        needs: os-update
        runs-on: ubuntu-latest
        steps:
            - shell: bash
              run: |
                sudo apt-get install make
                make --version

    make-version:
        needs: install-make
        runs-on: ubuntu-latest
        steps:
            - shell: bash
              run: |
                make --version
                echo "Make Version: $(make --version | head -n1) ,flag =  ${{ github.actor }}"


    make-docker-cmd:
        needs: install-make
        runs-on: ubuntu-latest
        steps:
            - shell: bash
              run: |
                 make docker_build IMG=testing-img-param