name: Parallel Jobs Test 
on: [push]
jobs:
  build-ubuntu:
    name: build and test on ubuntu
    runs-on: ubuntu-latest
    steps:
            - name: echo a string
              run: echo "Hello World"

            - name: Get environment versions
              run: |
                echo "Checking environment versions"
                echo "Node Version: $(node --version)"
                echo "NPM Version: $(npm --version)"
                echo "NuGet Version: $(nuget help | grep Version)"

  build-windows:
      name: build and test on windows
      runs-on: windows-latest
      steps:
            - name: echo a string
              run: echo "Hello World"

            - name: Get environment versions
              run: |
                echo "Checking environment versions"
                echo "Node Version: $(node --version)"
                echo "NPM Version: $(npm --version)"
                echo "NuGet Version: $(nuget help | grep Version)"