name: Terraform ci test 
run-name: ${{ github.actor }} is Testing Terraform github actions

on: [push]
#   push:
#     branches:
#       - master
#   pull_request:
#     branches:
#       - master

jobs:
    install-make:
        runs-on: ubuntu-latest
        steps:
            - shell: bash
              run: |
                sudo apt-get update
                sudo apt-get install make
                make --version
                echo "Make Version: $(make --version)  , flag = ${{ github.actor }} "
